[package]
name = "jfs"
version = "0.5.0"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
license = "MIT"
homepage = "https://github.com/flosse/rust-json-file-store"
repository = "https://github.com/flosse/rust-json-file-store"
documentation = "https://docs.rs/crate/jfs/"
description = "A JSON file store"
keywords = ["json", "file", "store", "db", "database"]
categories = ["database"]
edition = "2018"

[dependencies]
fs2 = "0.4"
uuid = { version = "0.7", features = ["v4"] }
serde = "1"
serde_json = "1"

[dev-dependencies]
serde_derive = { version = "1" }

[badges]
travis-ci = { repository = "flosse/rust-json-file-store" }
